[package]
name = "proper_path_tools"
version = "0.7.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/proper_path_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/proper_path_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/proper_path_tools"
description = """
Collection of algorithms and structures to handle paths properly.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

[features]
default = [ "enabled", "path_unique_folder_name" ]
full = [ "enabled", "path_unique_folder_name", "derive_serde" ]
no_std = []
use_alloc = [ "no_std" ]
enabled = [ "mod_interface/enabled" ]

path_unique_folder_name = []
derive_serde = [ "serde" ]

[dependencies]
regex = { version = "1.10.3" }
mod_interface = { workspace = true }
serde = { version = "1.0.197", optional = true, features = [ "derive" ] }

[dev-dependencies]
test_tools = { workspace = true }
